// Generated by gencpp from file SummerInternship/Simulate.msg
// DO NOT EDIT!


#ifndef SUMMERINTERNSHIP_MESSAGE_SIMULATE_H
#define SUMMERINTERNSHIP_MESSAGE_SIMULATE_H

#include <ros/service_traits.h>


#include <SummerInternship/SimulateRequest.h>
#include <SummerInternship/SimulateResponse.h>


namespace SummerInternship
{

struct Simulate
{

typedef SimulateRequest Request;
typedef SimulateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Simulate
} // namespace SummerInternship


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::SummerInternship::Simulate > {
  static const char* value()
  {
    return "65387222401ee76337106b3d608d2fbd";
  }

  static const char* value(const ::SummerInternship::Simulate&) { return value(); }
};

template<>
struct DataType< ::SummerInternship::Simulate > {
  static const char* value()
  {
    return "SummerInternship/Simulate";
  }

  static const char* value(const ::SummerInternship::Simulate&) { return value(); }
};


// service_traits::MD5Sum< ::SummerInternship::SimulateRequest> should match 
// service_traits::MD5Sum< ::SummerInternship::Simulate > 
template<>
struct MD5Sum< ::SummerInternship::SimulateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::SummerInternship::Simulate >::value();
  }
  static const char* value(const ::SummerInternship::SimulateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::SummerInternship::SimulateRequest> should match 
// service_traits::DataType< ::SummerInternship::Simulate > 
template<>
struct DataType< ::SummerInternship::SimulateRequest>
{
  static const char* value()
  {
    return DataType< ::SummerInternship::Simulate >::value();
  }
  static const char* value(const ::SummerInternship::SimulateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::SummerInternship::SimulateResponse> should match 
// service_traits::MD5Sum< ::SummerInternship::Simulate > 
template<>
struct MD5Sum< ::SummerInternship::SimulateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::SummerInternship::Simulate >::value();
  }
  static const char* value(const ::SummerInternship::SimulateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::SummerInternship::SimulateResponse> should match 
// service_traits::DataType< ::SummerInternship::Simulate > 
template<>
struct DataType< ::SummerInternship::SimulateResponse>
{
  static const char* value()
  {
    return DataType< ::SummerInternship::Simulate >::value();
  }
  static const char* value(const ::SummerInternship::SimulateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUMMERINTERNSHIP_MESSAGE_SIMULATE_H
